-- INSERT INTO category (description) VALUES ('American');
-- INSERT INTO category (description) VALUES ('Italian');
-- INSERT INTO category (description) VALUES ('Mexican');
-- INSERT INTO category (description) VALUES ('Fast Food');
--
-- INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Teaspoon');
-- INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Tablespoon');
-- INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Cup');
-- INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Pinch');
-- INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Ounce');
-- INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Each');
-- INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Dash');
-- INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Pint');
